### ISSUE TITLE
[Question] Is it possible to get type for each attack?

### ISSUE THREAD

**Issue by wooseopkim** [coavins/mhrise-coavins-dps#1]
I'm trying the RE Framework dev tool, but I'm still not sure if it is possible to get attack types. In other words I want some information like "this damage is done with Spirit Helm Breaker (Long Sword)." I'd like to make a PR to this repository, or fork myself with an option to analyze damage by attack types.

Plus, where can I see log outputs? Is there any way to open the log console? Thanks in advance.

**Comment by coavins** [comment]
I do plan to include a fully detailed breakdown like that in the future, allowing for a full report of damage dealt by each move for each combatant. PRs are absolutely welcome here; the best way to contribute to the effort right now would probably be to use the REFramework developer tools to search through the singletons and types to identify exactly how and where this information is stored in the engine. That has been the biggest time sink for me so far.

The script logs to the reframework log file in the game install directory (SteamLibrary\steamapps\common\MonsterHunterRise\re2_framework_log.txt). Lines added by this script are prefixed with "mhrise-coavins-dps:". There's not much in there so far, for example it doesn't log all combat data yet for use by external tools.

**Comment by wooseopkim** [comment]
Good news: [a PR of mine](https://github.com/praydog/REFramework/pull/239) got merged to REFramework, and we can now search by method signature! It should be easier, or at least less harder, to find what method to call.

**Comment by wooseopkim** [comment]
Since this was a question or a feature request and for that `Discussions` tab would be more appropriate, I'm closing this issue now.
