### ISSUE TITLE
CJK characters show as question mark (?)

### ISSUE THREAD

**Issue by liu2z2** [coavins/mhrise-coavins-dps#13]
**Describe the bug**
When there is player with name that has [CJK characters](https://en.wikipedia.org/wiki/CJK_characters), the name on the bar shows with question marks (?)

**Steps to Reproduce**
For example:
1. Configure the UI with the generated GUI
2. Enter quest where there is player with name that has CJK characters
3. Name on the DPS bar shows ???

**Expected behavior**
Name should show exactly as is in the game

**Screenshots**
See below. The display looks fine except the LBG user `究極白毛控`, which shows as `?????`
![image](https://user-images.githubusercontent.com/55007630/151294380-c70a9d59-6af0-4363-bd9d-d3a5fb6f2d7d.png)

**REFramework commit hash** (if known): `066d6993`

**Comment by coavins** [comment]
Thank you for the report. This is a known reframework issue and is being worked on. See pull request praydog/reframework#213 for details.

**Comment by praydog** [comment]
Font improvements branch was merged to master. It has the possibility to render these characters, but you need to manually specify a range of characters and font.

Plugins system was also merged to master.

@cursey has made a plugin to add better rendering APIs without modifying REFramework. 
https://github.com/cursey/reframework-d2d

Feedback on both of these would be appreciated, and if they meet your needs.

**Comment by cursey** [comment]
> Thank you for the report. This is a known reframework issue and is being worked on. See pull request [praydog/REFramework#213](https://github.com/praydog/REFramework/pull/213) for details.

I have merged this PR into master. And it does enable support for other languages, but it is tedious as you have to provide a compatible font and specify the Unicode character ranges you wish to load from that font. This is just simply the way ImGui works, and it's far from ideal. 

That is why I created a plugin, the one @praydog linked, https://github.com/cursey/reframework-d2d. It lets you specify just a system font, and will work with any language even if the desired font doesn't support those characters (it will just choose a font that does support them). I will release this plugin on nexus as soon as the next version of REFramework is released on nexus and fully plan on supporting this plugin for overlay style mods going forward.

**Comment by coavins** [comment]
Resolved by 87bec78

Thank you @cursey and @praydog for your incredible work.
