### ISSUE TITLE
Auto reset data after combat

### ISSUE THREAD

**Issue by kingrodriguez** [coavins/mhrise-coavins-dps#2]
### Current behavior
After finishing a mission, the damage is still "saved". When starting a new mission and hit a (large) monster, the damage keeps adding to the values from the previous run.

### Expected behavior
Latest when damage is done to a new monster in a new quest, the damage should reset to 0.

### Quick fix
- Make a note about the behavior in the docs.
- Reset the script (also resets the settings)

**Comment by coavins** [comment]
Thanks for the report. I have just posted release 1.5.2 which fixes this issue in commit 0bcde32.
