### ISSUE TITLE
Typo in ENUM_KEYBOARD_KEY

### ISSUE THREAD

**Issue by GreenComfyTea** [coavins/mhrise-coavins-dps#27]
**The bug:**
`[73]` is `J` instead of  `I` and `[74]` is missed but should be  `J`.
`Lines 110-114:`
```
ENUM_KEYBOARD_KEY[71] = 'G'
ENUM_KEYBOARD_KEY[72] = 'H'
ENUM_KEYBOARD_KEY[73] = 'J'
ENUM_KEYBOARD_KEY[75] = 'K'
ENUM_KEYBOARD_KEY[76] = 'L'
```

**Fix:**

```
ENUM_KEYBOARD_KEY[71] = 'G'
ENUM_KEYBOARD_KEY[72] = 'H'
ENUM_KEYBOARD_KEY[73] = 'I'
ENUM_KEYBOARD_KEY[74] = 'J'
ENUM_KEYBOARD_KEY[75] = 'K'
ENUM_KEYBOARD_KEY[76] = 'L'
```
**More:**
There are also other weird behaviors with in-game keys as well as rename suggestions to match ANSI/ISO/IME keyboard layout. Posting it here just so you would be aware and could find it easily if needed.

`[3]` is called `Cancel`. Rename suggestion: `ControlBreak`.
`[18]` is called `Menu`. Rename suggestion: `Alt`.
`[19]` is called `Pause`. Rename suggestion: `PauseBreak`.
`[20]` is called `Capital`. Rename suggestion: `CapsLock`.
`[21]` is called `Kana`. Rename suggestion: `Kana/Hangual/Hangul`.
`[22]` is missing. It's `IME On`.
`[25]` is called `Hanja`. Rename suggestion: `Hanja/Kanji`.
`[26]` is missing. It's `IME Off`.
`[42]` is called `Print`. Rename suggestion: `PrintScreen`.
`[48]`-`[57]` are called `Alpha0` - `Alpha9`. Rename suggestion: `0` - `9`.

**`[61]` is missing. According to Microsoft Docs it is `=+` key but it is not registered by the game.**

**`[70]` is `F`. The game registers it. But it also registers [254] when pressing `F`.**

`[106]` is called `Multiply`. Rename suggestion: `Numpad Multiply` or `Numpad *`.
`[107]` is called `Add`. Rename suggestion: `Numpad Add` or `Numpad +`.
`[108]` is called `Separator`. Rename suggestion: `Numpad Separator`.
`[109]` is called `Subtract`. Rename suggestion: `Numpad Subtract` or `Numpad -`.
`[110]` is called `Decimal`. Rename suggestion: `Numpad Decimal` or `Numpad .`.
`[111]` is called `Divide`. Rename suggestion: `Numpad Divide` or `Numpad /`.
`[145]` is called `Scroll`. Rename suggestion: `ScrollLock`.
`[162]`  is called `LControl`. Rename suggestion: `LeftControl`.
`[163]`  is called `RControl`. Rename suggestion: `RightControl`.
`[164]`  is called `LMenu`. Rename suggestion: `LAlt` or `LeftAlt`.
`[165]`  is called `RMenu`. Rename suggestion: `RAlt` or `RightAlt`.

**`[186]` is `OEM_1`. According to Microsoft Docs it is `;:` key but it is not registered by the game. Instead the game registers `[187]` when pressing `;:` key.**

`[186]` is called `OEM_1`. Rename suggestion: `;:`.
`[187]` is called `OEM_Plus`. Rename suggestion: `+`.
`[188]` is called `OEM_Comma`. Rename suggestion: `,<`.
`[189]` is called `OEM_Minus`. Rename suggestion: `-`.
`[190]` is called `OEM_Period`. Rename suggestion: `.>`.
`[191]` is called `Slash`. Rename suggestion: `/?`.

**`[192]` is `OEM_3`. According to Microsoft Docs it is `\~` key but it is not registered by the game.**

`[192]` is called `OEM_3`. Rename suggestion: `~`.
`[219]` is called `OEM_4`. Rename suggestion: `[{`.
`[220]` is called `OEM_5`. Rename suggestion: `\|`.
`[221]` is called `OEM_6`. Rename suggestion: `]}`.

**`[222]` is `OEM_7`. According to Microsoft Docs it is `'"` key but it is not registered by the game. Instead the game registers `[106]` when pressing `' "` key.**

`[222]` is called `OEM_7`. Rename suggestion: `'"`.
`[226]` is called `OEM_102`. Rename suggestion: `<>`.

**`[220]` is called `BackSlash` and its repeated second time. Should be removed.**

`[254]` is called `DefinedEnter`. Rename suggestion: `Clear`.

**Comment by coavins** [comment]
Hey thanks for this, I'll make sure to correct this for the next release. It was so tedious copying down all these keys from the enum, I'm not surprised I made a mistake.

I'll probably rename some of these, but I do also want to try to stay as close as possible to the names used internally in the game.
