### ISSUE TITLE
Data not reseting ?

### ISSUE THREAD

**Issue by Diyagi** [coavins/mhrise-coavins-dps#3]
The data from the previous expedition is not being rebooted, and is being carried forward.
![image](https://user-images.githubusercontent.com/9062212/150840283-450f0630-9884-471b-a064-2ac1b7d8f1b1.png)

Also, when i try to Reset Scripts via the framework menu, the game crashes, don't know if it's related to this plugin thought, as i dont know how to read the dump files. (It was fine before i updated this plugin though)

**Comment by coavins** [comment]
This should be fixed in the new [version 1.5.2](https://github.com/coavins/mhrise-coavins-dps/releases/tag/v1.5.2), please download that and give it a try.

Let me know if you are still experiencing this issue with the latest version.

**Comment by Diyagi** [comment]
Oh, sorry, i updated before sleeping and didn't see the new update

**Comment by coavins** [comment]
> Also, when i try to Reset Scripts via the framework menu, the game crashes, don't know if it's related to this plugin thought, as i dont know how to read the dump files. (It was fine before i updated this plugin though)

I haven't heard this issue reported yet, try removing all other REFramework scripts and other mods and see if the crash still occurs.
