### ISSUE TITLE
The cart that ends the quest isn't captured

### ISSUE THREAD

**Issue by coavins** [coavins/mhrise-coavins-dps#32]
**Describe the bug**
The last cart of the quest doesn't seem to get recorded. This would probably be annoying for anyone who wanted to export and aggregate their data.

**Steps to Reproduce**
1. Enter quest
2. Cart three times
3. See player isn't credited with third cart

**Comment by SeppNel** [comment]
It is counted in the export, just not displayed in game for some reason.
Ex: [02-07-2022_09.txt](https://github.com/coavins/mhrise-coavins-dps/files/9034428/02-07-2022_09.txt)
 In that quest we carted 4 times (we had insurance) and it is exported correctly

**Comment by coavins** [comment]
Thanks, I fixed it not showing up in-game.
