### ISSUE TITLE
Felyne Fireworks not counted

### ISSUE THREAD

**Issue by SeppNel** [coavins/mhrise-coavins-dps#34]
**Describe the bug**
The new Felyne Fireworks palico skill is not credited to the corresponding palico

**Steps to Reproduce**
1. Use a palico with Felyne Fireworks
2. Enter quest
3. Use it and hit with it
4. See it not credited

**Expected behavior**
Damage beign credited to the palico who used it.

**Comment by coavins** [comment]
Thank you, this has been resolved for the next release.

There were two new buddy damage types, I went ahead and included the second type as well even though I'm not sure yet what move is using it.
