### ISSUE TITLE
adding a new translation(zh-cn)

### ISSUE THREAD

**Issue by qizhouzhangsheng** [coavins/mhrise-coavins-dps#36]
{
	"colors": {
		"BAR_BG": "背景栏",
		"BAR_DMG_AILMENT": "疾病累积",
		"BAR_DMG_BLAST": "爆炸伤害",
		"BAR_DMG_ELEMENT_UNIQUE_1": "P1 主要输出伤害",
		"BAR_DMG_ELEMENT_UNIQUE_2": "P2 主要输出伤害",
		"BAR_DMG_ELEMENT_UNIQUE_3": "P3 主要输出伤害",
		"BAR_DMG_ELEMENT_UNIQUE_4": "P4 主要输出伤害",
		"BAR_DMG_ELEMENT": "主要输出伤害",
		"BAR_DMG_OTHER": "额外输出伤害",
		"BAR_DMG_OTOMO": "宠物输出伤害",
		"BAR_DMG_PHYSICAL_UNIQUE_1": "P1 物理输出伤害",
		"BAR_DMG_PHYSICAL_UNIQUE_2": "P2 物理输出伤害",
		"BAR_DMG_PHYSICAL_UNIQUE_3": "P3 物理输出伤害",
		"BAR_DMG_PHYSICAL_UNIQUE_4": "P4 物理输出伤害",
		"BAR_DMG_PHYSICAL": "物理输出伤害",
		"BAR_DMG_POISON": "毒药输出伤害",
		"BAR_OUTLINE": "大纲栏 ",
		"OTOMO": "同伴",
		"PLAYER_1": "玩家 1",
		"PLAYER_2": "玩家 2",
		"PLAYER_3": "玩家 3",
		"PLAYER_4": "玩家 4",
		"SERVANT": "盟友",
		"TITLE_BG": "背景标题",
		"TITLE_FG": "前标题"
	},
	"column_headers": {
		"1": "无",
		"2": "猎人等级",
		"3": "名字",
		"4": "秒伤",
		"5": "总输出",
		"6": "团队占比",
		"7": "Best%",
		"8": "攻击命中次数",
		"9": "最大攻击命中次数",
		"10": "qDPS",
		"11": "状态",
		"12": "毒药",
		"13": "爆炸",
		"14": "暴击率",
		"15": "Weak%",
		"16": "pDPS",
		"17": "Physical",
		"18": "Element",
		"19": "Carts",
		"20": "大师等级"
	},
	"damage_types": {
		"BallistaHate": "BallistaHate",
		"BarrelBombLarge": "Large Barrel Bomb",
		"BarrelBombSmall": "Barrel Bomb",
		"CaptureBullet": "Tranq Ammo",
		"CaptureSmokeBomb": "Tranq Bomb",
		"DetonationGrenade": "detonationgrenade",
		"EcBatExplode": "EcBatExplode",
		"EcFlash": "EcFlash",
		"EcForestWallShooter": "EcForestWallShooter",
		"EcPenetrateFish": "EcPenetrateFish",
		"EcPiranha": "EcPiranha",
		"EcSandWallShooter": "EcSandWallShooter",
		"EcSwampLeech": "EcSwampLeech",
		"EcWallTrapBugExplode": "EcWallTrapBugExplode",
		"Fg005": "Fg005",
		"FlashBoll": "FlashBoll",
		"HmBallista": "Ballista",
		"HmCannon": "榴弹炮",
		"HmDragnator": "Dragonator",
		"HmFlameThrower": "Wyvernfire",
		"HmGatling": "Machine Cannon",
		"HmNpc": "Defenders",
		"HmTrap": "Bamboo Bomb",
		"Monster": "Monster",
		"Kabutowari": "Spirit Helm Breaker",
		"Kunai": "Kunai",
		"Makimushi": "makimushi",
		"marionette": "Wyvern Riding",
		"Max": "未知",
		"Nitro": "nitro",
		"OnibiMine": "onibimine",
		"OtAirouShell014": "OtAirouShell014",
		"OtAirouShell102": "Felyne Fireworks",
		"Otomo": "伙伴",
		"PlayerWeapon": "玩家武器",
		"WaterBeetle": "水甲虫"
	},
	"hotkeys": {
		"MONSTER_NEXT": "下一个怪物",
		"MONSTER_PREV": "上一个怪物",
		"TOGGLE_OVERLAY": "切换覆盖"
	},
	"keys": {
		"0": "None",
		"1": "LButton",
		"2": "RButton",
		"3": "ControlBreak",
		"4": "MButton",
		"5": "XButton1",
		"6": "XButton2",
		"8": "Back",
		"9": "Tab",
		"12": "Clear",
		"13": "Enter",
		"19": "PauseBreak",
		"20": "CapsLock",
		"21": "Kana/Hangual/Hangul",
		"22": "IME On",
		"23": "Junja",
		"24": "Final",
		"25": "Hanja/Kanji",
		"26": "IME Off",
		"27": "Escape",
		"28": "Convert",
		"29": "NonConvert",
		"30": "Accept",
		"31": "ModeChange",
		"32": "Space",
		"33": "PageUp",
		"34": "PageDown",
		"35": "End",
		"36": "Home",
		"37": "Left",
		"38": "Up",
		"39": "Right",
		"40": "Down",
		"41": "Select",
		"42": "PrintScreen",
		"43": "Execute",
		"44": "SnapShot",
		"45": "Insert",
		"46": "Delete",
		"47": "Help",
		"48": "0",
		"49": "1",
		"50": "2",
		"51": "3",
		"52": "4",
		"53": "5",
		"54": "6",
		"55": "7",
		"56": "8",
		"57": "9",
		"65": "A",
		"66": "B",
		"67": "C",
		"68": "D",
		"69": "E",
		"70": "F",
		"71": "G",
		"72": "H",
		"73": "I",
		"74": "J",
		"75": "K",
		"76": "L",
		"77": "M",
		"78": "N",
		"79": "O",
		"80": "P",
		"81": "Q",
		"82": "R",
		"83": "S",
		"84": "T",
		"85": "U",
		"86": "V",
		"87": "W",
		"88": "X",
		"89": "Y",
		"90": "Z",
		"91": "LWin",
		"92": "RWin",
		"93": "Apps",
		"95": "Sleep",
		"96": "Numpad 0",
		"97": "Numpad 1",
		"98": "Numpad 2",
		"99": "Numpad 3",
		"100": "Numpad 4",
		"101": "Numpad 5",
		"102": "Numpad 6",
		"103": "Numpad 7",
		"104": "Numpad 8",
		"105": "Numpad 9",
		"106": "Numpad Multiply",
		"107": "Numpad Plus",
		"108": "Numpad Separator",
		"109": "Numpad Minus",
		"110": "Numpad Period",
		"111": "Numpad Divide",
		"112": "F1",
		"113": "F2",
		"114": "F3",
		"115": "F4",
		"116": "F5",
		"117": "F6",
		"118": "F7",
		"119": "F8",
		"120": "F9",
		"121": "F10",
		"122": "F11",
		"123": "F12",
		"124": "F13",
		"125": "F14",
		"126": "F15",
		"127": "F16",
		"128": "F17",
		"129": "F18",
		"130": "F19",
		"131": "F20",
		"132": "F21",
		"133": "F22",
		"134": "F23",
		"135": "F24",
		"144": "NumLock",
		"145": "ScrollLock",
		"146": "NumPad Enter",
		"160": "Left Shift",
		"161": "Right Shift",
		"162": "Left Control",
		"163": "Right Control",
		"164": "Left Alt",
		"165": "Right Alt",
		"186": ";",
		"187": "+",
		"188": ",",
		"189": "-",
		"190": ".",
		"191": "/",
		"192": "`",
		"219": "[",
		"220": "\\",
		"221": "]",
		"222": "'",
		"223": "OEM_8",
		"226": "<",
		"254": "Clear",
		"255": "Backspace"
	},
	"messages": {
		"btn_apply_colorscheme": "应用配色方案",
		"btn_apply_language": "设置语言",
		"btn_apply_preset": "应用预设",
		"btn_clear_data": "清除作战数据",
		"btn_close_settings": "关闭设置",
		"btn_load_settings": "载入设置",
		"btn_open_debug": "打开 debug 菜单",
		"btn_open_settings": "打开设置",
		"btn_reset_default_colors": "重置为默认颜色",
		"btn_reset_default": "重置为默认值",
		"btn_save_settings": "保存设置",
		"btn_set_hotkeys": "更改热键",
		"Color_Scheme": "配色方案",
		"Column": "圆柱",
		"Enabled": "启用",
		"Languages": "语言",
		"msg_appearance": "外貌",
		"msg_color": "颜色",
		"msg_columns": "选择圆柱",
		"msg_customize_colors": "自定义颜色",
		"msg_damagetype_general": "通用",
		"msg_damagetype_huntinginstallations": "安装",
		"msg_damagetype_items": "项目",
		"msg_damagetype_moves": "移动",
		"msg_damagetype_otomo": "伙计",
		"msg_damagetype_unknown_help": "如果你知道这些是用来做什么的，请告诉我！",
		"msg_damagetype_unknown": "未知",
		"msg_damagetype": "按损坏类型筛选（高级）",
		"msg_debug": "Debug",
		"msg_fighter_boss": "大型怪物",
		"msg_fighter_other": "小怪物、暴怒的村民等",
		"msg_fighter_otomo": "玩家伙伴（未合并时）",
		"msg_fighter_player": "玩家",
		"msg_fighter_servant": "盟友",
		"msg_fighter_servantotomo": "盟友伙伴（未合并时）",
		"msg_fighters": "包括战斗机",
		"msg_general": "通用",
		"msg_header": "标题",
		"msg_not_use_hooks": "不要使用SDK挂钩",
		"msg_plugin_missing1": "缺少插件：reframework-d2d",
		"msg_plugin_missing2": "某些功能不可用",
		"msg_presets": "预设",
		"msg_press_key": "按键...",
		"msg_privacy": "隐私",
		"msg_report": "报告",
		"msg_rows": "Rows",
		"msg_rules": "规则",
		"msg_sizeandposition_help1": "缩放覆盖",
		"msg_sizeandposition_help2": "保存更改并重置脚本以更改字体大小",
		"msg_sizeandposition": "尺寸和位置",
		"msg_target_help": "你在任务中遇到的怪物将出现在这里.",
		"msg_target_none": "(还没有怪物)",
		"msg_target": "按目标筛选",
		"msg_text_help1": "需要插件：reframework-d2d",
		"msg_text_help2": "保存更改并重置脚本以将更改应用于字体",
		"msg_text": "字体",
		"msg_title": "标题",
		"msg_total": "总计",
		"msg_width": "列宽",
		"Settings": "设置"
	},
	"options": {
		"ADD_TARGETS_TO_REPORT": "自动筛选任务目标",
		"AUTO_SAVE": "自动保存所有设置",
		"COMBINE_ALL_OTHERS": "合并除你之外的所有人",
		"COMBINE_OTOMO_WITH_HUNTER": "将所有伙伴与他们的猎人结合在一起",
		"CONDITION_LIKE_DAMAGE": "疾病累积视为损害",
		"DEBUG_SHOW_ATTACKER_ID": "显示攻击者ID而不是HR",
		"DEBUG_SHOW_MISSING_DAMAGE": "在标题栏中显示表中未说明的任何伤害",
		"DRAW_BAR_COLORBLOCK": "显示颜色立方体",
		"DRAW_BAR_OUTLINES": "显示每行概述",
		"DRAW_BAR_RELATIVE_TO_PARTY": "伤害栏将代表团队总DPS的份额",
		"DRAW_BAR_REVEAL_RANK": "显示玩家排名",
		"DRAW_BAR_REVEAL_RANK_1": "隐藏",
		"DRAW_BAR_REVEAL_RANK_2": "显示 HR",
		"DRAW_BAR_REVEAL_RANK_3": "显示 MR",
		"DRAW_BAR_TEXT_NAME_USE_REAL_NAMES": "显示角色名称",
		"DRAW_BAR_TEXT_YOU": "显示 \"你\" 在你的那行",
		"DRAW_BAR_USE_PLAYER_COLORS": "用指定的颜色显示球员栏",
		"DRAW_BAR_USE_UNIQUE_COLORS": "以不同颜色显示每种类型的伤害",
		"DRAW_HEADER_BACKGROUND": "显示标题背景",
		"DRAW_HEADER_HEIGHT": "收割台高度",
		"DRAW_HEADER": "显示标题",
		"DRAW_TABLE_BACKGROUND": "显示行背景",
		"DRAW_TITLE_BACKGROUND": "显示标题背景",
		"DRAW_TITLE_HEIGHT": "标题高度",
		"DRAW_TITLE_MONSTER": "在标题中显示选定的怪物",
		"DRAW_TITLE_TEXT": "显示标题文本",
		"DRAW_TITLE": "显示标题",
		"DRAW_TOTAL": "显示总计",
		"DRAW_TOTAL_BACKGROUND": "显示总背景",
		"FONT_FAMILY": "字体系列",
		"HIDE_COMBINED_OTHERS": "只给你看",
		"HIDE_OVERLAY_IN_VILLAGE": "在村庄时隐藏覆盖层",
		"MARIONETTE_IS_PLAYER_DMG": "威文骑行造成伤害的信用卡骑手",
		"PDPS_BASED_ON_FIRST_STRIKE": "pDPS 从人物的第一次攻击开始计算",
		"SAVE_RESULTS_TO_DISK": "任务完成后将结果保存到磁盘",
		"SHOW_MISSING_DAMAGE": "显示未显示的损坏程度",
		"SHOW_TEST_DATA_WHILE_MENU_IS_OPEN": "菜单打开时显示测试数据",
		"TABLE_GROWS_UPWARD": "图表向上而不是向下增长",
		"TABLE_HEADER_TEXT_OFFSET_X": "标题文本偏移X",
		"TABLE_ROW_PADDING": "行填充",
		"TABLE_ROW_TEXT_OFFSET_X": "文本偏移Y",
		"TABLE_ROW_TEXT_OFFSET_Y": "文本偏移Y",
		"TABLE_ROWH": "行高度",
		"TABLE_SCALE": "比例因子",
		"TABLE_SORT_ASC": "反向排序顺序",
		"TABLE_SORT_IN_ORDER": "按玩家排序",
		"TABLE_TOTAL_TEXT_OFFSET_X": "总文本偏移量X",
		"TABLE_WIDTH": "工作台宽度",
		"TABLE_X": "水平位置",
		"TABLE_Y": "垂直位置",
		"TEXT_DRAW_SHADOWS": "绘制文字阴影",
		"TEXT_SHADOW_OFFSET_X": "文本阴影偏移X",
		"TEXT_SHADOW_OFFSET_Y": "文本阴影偏移Y",
		"UPDATE_RATE": "更新频率（秒）",
		"USE_MINIMAL_BARS": "使用极简风格的伤害栏"
	}
}

**Comment by coavins** [comment]
#40 was merged, this translation will be included in the next release. Thanks!
