### ISSUE TITLE
Add a hotkey to hide/show the table overlay

### ISSUE THREAD

**Issue by coavins** [coavins/mhrise-coavins-dps#4]
The script should somehow register a hotkey to allow the user to quickly toggle the display of the table overlay.

**Comment by Diyagi** [comment]
Just a quick note on this,
Some mods forget to check for modifiers on keyboard (Like Shift, ctrl, alt), this can impact other mods that uses the same key with the modifer, so, its a good ideia to check for those.

For exemple, first mod uses Home to show the UI, the second one uses Ctrl+Home, if the first mod dont check for the modfiers, when the user press Ctrl+Home, both mods will show the UI.

**Comment by coavins** [comment]
Thanks for the tip! I'm working on this now and I would have missed that.
