### ISSUE TITLE
Clear table data when leaving the training area

### ISSUE THREAD

**Issue by coavins** [coavins/mhrise-coavins-dps#5]
Currently if you fight in the training area in the village and then enter a quest, the data from the training dummy will be retained in the monster cache. This data should be cleared when the player either enters another village area or enters a quest.

**Comment by Diyagi** [comment]
The function `endTrainingRoom` from `snow.stage.StageManager` seems to be called both when the player leave the training room to another village location and when the player leave the training room to a quest.

**Comment by coavins** [comment]
Thanks! That seems to do the job.
